export const data_values_warenhouse = [
  {
  "id": 1,
  "week": "Week 1",
  "security_stock": "50",
  "consumption": 30,
  "inicial_inventory": "100",
  "final_stock": 20,
},
{
  "id": 2,
  "week": "Week 2",
  "security_stock": "30",
  "consumption": 20,
  "inicial_inventory": "60",
  "final_stock": 40,
},
{
  "id": 3,
  "week": "Week 3",
  "security_stock": "35",
  "consumption": 25,
  "inicial_inventory": "75",
  "final_stock": 50,
},
{
  "id": 4,
  "week": "Week 4",
  "security_stock": "20",
  "consumption": 10,
  "inicial_inventory": "40",
  "final_stock": 30,
},
{
  "id": 5,
  "week": "Week 5",
  "security_stock": "55",
  "consumption": 35,
  "inicial_inventory": "110",
  "final_stock": 75,
},
{
  "id": 6,
  "week": "Week 6",
  "security_stock": "60",
  "consumption": 40,
  "inicial_inventory": "120",
  "final_stock": 80,
},
{
  "id": 7,
  "week": "Week 7",
  "security_stock": "35",
  "consumption": 25,
  "inicial_inventory": "70",
  "final_stock": 45,
},
{
  "id": 8,
  "week": "Week 8",
  "security_stock": "40",
  "consumption": 30,
  "inicial_inventory": "80",
  "final_stock": 50,
},
{
  "id": 9,
  "week": "Week 9",
  "security_stock": "15",
  "consumption": 10,
  "inicial_inventory": "40",
  "final_stock": 30,
},
{
  "id": 10,
  "week": "Week 10",
  "security_stock": "35",
  "consumption": 25,
  "inicial_inventory": "70",
  "final_stock": 45,
}]
