export const data_values = [
  {
  "id": 1,
  "order_received": "50",
  "week": 1,
  "order_placed": "30",
}, {
  "id": 2,
  "order_received": "60",
  "week": 2,
  "order_placed": "40",
}, {
  "id": 3,
  "order_received": "70",
  "week": 3,
  "order_placed": "55",
}, {
  "id": 4,
  "order_received": "80",
  "week": 4,
  "order_placed": "50",
}, {
  "id": 5,
  "order_received": "55",
  "week": 5,
  "order_placed": "35",
}, {
  "id": 6,
  "order_received": "45",
  "week": 6,
  "order_placed": "30",
}, {
  "id": 7,
  "order_received": "30",
  "week": 7,
  "order_placed": "15",
}, {
  "id": 8,
  "order_received": "25",
  "week": 8,
  "order_placed": "15",
}, {
  "id": 9,
  "order_received": "80",
  "week": 9,
  "order_placed": "40",
}]
